package openssf.omega.policy.autogenerated.cwe.cwe_306

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_306
# title: "CWE-306: Missing Authentication for Critical Function"
# methodology: >
#   The product does not perform any authentication for functionality that requires a provable user identity or consumes a significant amount of resources.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-306" in assertion.predicate.content.tags
    }
}