package openssf.omega.policy.autogenerated.cwe.cwe_663

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_663
# title: "CWE-663: Use of a Non-reentrant Function in a Concurrent Context"
# methodology: >
#   The product calls a non-reentrant function in a concurrent context in which a competing code sequence (e.g. thread or signal handler) may have an opportunity to call the same function or otherwise influence its state.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-663" in assertion.predicate.content.tags
    }
}