package openssf.omega.policy.autogenerated.cwe.cwe_588

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_588
# title: "CWE-588: Attempt to Access Child of a Non-structure Pointer"
# methodology: >
#   Casting a non-structure type to a structure type and accessing a field can lead to memory access errors or data corruption.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-588" in assertion.predicate.content.tags
    }
}