package openssf.omega.policy.autogenerated.cwe.cwe_120

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_120
# title: "CWE-120: Buffer Copy without Checking Size of Input ('Classic Buffer Overflow')"
# methodology: >
#   The product copies an input buffer to an output buffer without verifying that the size of the input buffer is less than the size of the output buffer, leading to a buffer overflow.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-120" in assertion.predicate.content.tags
    }
}