package openssf.omega.policy.autogenerated.cwe.cwe_309

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_309
# title: "CWE-309: Use of Password System for Primary Authentication"
# methodology: >
#   The use of password systems as the primary means of authentication may be subject to several flaws or shortcomings, each reducing the effectiveness of the mechanism.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-309" in assertion.predicate.content.tags
    }
}