package openssf.omega.policy.autogenerated.cwe.cwe_762

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_762
# title: "CWE-762: Mismatched Memory Management Routines"
# methodology: >
#   The product attempts to return a memory resource to the system, but it calls a release function that is not compatible with the function that was originally used to allocate that resource.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-762" in assertion.predicate.content.tags
    }
}