package openssf.omega.policy.autogenerated.cwe.cwe_829

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_829
# title: "CWE-829: Inclusion of Functionality from Untrusted Control Sphere"
# methodology: >
#   The product imports, requires, or includes executable functionality (such as a library) from a source that is outside of the intended control sphere.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-829" in assertion.predicate.content.tags
    }
}