package openssf.omega.policy.autogenerated.cwe.cwe_359

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_359
# title: "CWE-359: Exposure of Private Personal Information to an Unauthorized Actor"
# methodology: >
#   The product does not properly prevent a person's private, personal information from being accessed by actors who either (1) are not explicitly authorized to access the information or (2) do not have the implicit consent of the person about whom the information is collected.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-359" in assertion.predicate.content.tags
    }
}