package openssf.omega.policy.autogenerated.cwe.cwe_1074

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_1074
# title: "CWE-1074: Class with Excessively Deep Inheritance"
# methodology: >
#   A class has an inheritance level that is too high, i.e., it has a large number of parent classes.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-1074" in assertion.predicate.content.tags
    }
}