package openssf.omega.policy.autogenerated.cwe.cwe_538

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_538
# title: "CWE-538: Insertion of Sensitive Information into Externally-Accessible File or Directory"
# methodology: >
#   The product places sensitive information into files or directories that are accessible to actors who are allowed to have access to the files, but not to the sensitive information.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-538" in assertion.predicate.content.tags
    }
}