package openssf.omega.policy.autogenerated.cwe.cwe_1322

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_1322
# title: "CWE-1322: Use of Blocking Code in Single-threaded, Non-blocking Context"
# methodology: >
#   The product uses a non-blocking model that relies on a single threaded process for features such as scalability, but it contains code that can block when it is invoked.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-1322" in assertion.predicate.content.tags
    }
}