package openssf.omega.policy.autogenerated.cwe.cwe_497

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_497
# title: "CWE-497: Exposure of Sensitive System Information to an Unauthorized Control Sphere"
# methodology: >
#   The product does not properly prevent sensitive system-level information from being accessed by unauthorized actors who do not have the same level of access to the underlying system as the product does.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-497" in assertion.predicate.content.tags
    }
}