package openssf.omega.policy.autogenerated.cwe.cwe_1332

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_1332
# title: "CWE-1332: Improper Handling of Faults that Lead to Instruction Skips"
# methodology: >
#   The device is missing or incorrectly implements circuitry or sensors that detect and mitigate the skipping of security-critical CPU instructions when they occur.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-1332" in assertion.predicate.content.tags
    }
}