package openssf.omega.policy.autogenerated.cwe.cwe_1176

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_1176
# title: "CWE-1176: Inefficient CPU Computation"
# methodology: >
#   The product performs CPU computations using algorithms that are not as efficient as they could be for the needs of the developer, i.e., the computations can be optimized further.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-1176" in assertion.predicate.content.tags
    }
}