package openssf.omega.policy.autogenerated.cwe.cwe_1052

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_1052
# title: "CWE-1052: Excessive Use of Hard-Coded Literals in Initialization"
# methodology: >
#   The product initializes a data element using a hard-coded literal that is not a simple integer or static constant element.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-1052" in assertion.predicate.content.tags
    }
}