package openssf.omega.policy.autogenerated.cwe.cwe_641

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_641
# title: "CWE-641: Improper Restriction of Names for Files and Other Resources"
# methodology: >
#   The product constructs the name of a file or other resource using input from an upstream component, but it does not restrict or incorrectly restricts the resulting name.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-641" in assertion.predicate.content.tags
    }
}