package openssf.omega.policy.autogenerated.cwe.cwe_508

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_508
# title: "CWE-508: Non-Replicating Malicious Code"
# methodology: >
#   Non-replicating malicious code only resides on the target system or product that is attacked; it does not attempt to spread to other systems.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-508" in assertion.predicate.content.tags
    }
}