package openssf.omega.policy.autogenerated.cwe.cwe_680

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_680
# title: "CWE-680: Integer Overflow to Buffer Overflow"
# methodology: >
#   The product performs a calculation to determine how much memory to allocate, but an integer overflow can occur that causes less memory to be allocated than expected, leading to a buffer overflow.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-680" in assertion.predicate.content.tags
    }
}