package openssf.omega.policy.autogenerated.cwe.cwe_435

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_435
# title: "CWE-435: Improper Interaction Between Multiple Correctly-Behaving Entities"
# methodology: >
#   An interaction error occurs when two entities have correct behavior when running independently of each other, but when they are integrated as components in a larger system or process, they introduce incorrect behaviors that may cause resultant weaknesses.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-435" in assertion.predicate.content.tags
    }
}