package openssf.omega.policy.autogenerated.cwe.cwe_916

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_916
# title: "CWE-916: Use of Password Hash With Insufficient Computational Effort"
# methodology: >
#   The product generates a hash for a password, but it uses a scheme that does not provide a sufficient level of computational effort that would make password cracking attacks infeasible or expensive.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-916" in assertion.predicate.content.tags
    }
}