package openssf.omega.policy.autogenerated.cwe.cwe_1318

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_1318
# title: "CWE-1318: Missing Support for Security Features in On-chip Fabrics or Buses"
# methodology: >
#   On-chip fabrics or buses either do not support or are not configured to support privilege separation or other security features, such as access control.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-1318" in assertion.predicate.content.tags
    }
}