package openssf.omega.policy.autogenerated.cwe.cwe_1077

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_1077
# title: "CWE-1077: Floating Point Comparison with Incorrect Operator"
# methodology: >
#   The code performs a comparison such as an equality test between two float (floating point) values, but it uses comparison operators that do not account for the possibility of loss of precision.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-1077" in assertion.predicate.content.tags
    }
}