package openssf.omega.policy.autogenerated.cwe.cwe_1272

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_1272
# title: "CWE-1272: Sensitive Information Uncleared Before Debug/Power State Transition"
# methodology: >
#   The product performs a power or debug state transition, but it does not clear sensitive information that should no longer be accessible due to changes to information access restrictions.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-1272" in assertion.predicate.content.tags
    }
}