package openssf.omega.policy.autogenerated.cwe.cwe_202

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_202
# title: "CWE-202: Exposure of Sensitive Information Through Data Queries"
# methodology: >
#   When trying to keep information confidential, an attacker can often infer some of the information by using statistics.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-202" in assertion.predicate.content.tags
    }
}