package openssf.omega.policy.autogenerated.cwe.cwe_940

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_940
# title: "CWE-940: Improper Verification of Source of a Communication Channel"
# methodology: >
#   The product establishes a communication channel to handle an incoming request that has been initiated by an actor, but it does not properly verify that the request is coming from the expected origin.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-940" in assertion.predicate.content.tags
    }
}