package openssf.omega.policy.autogenerated.cwe.cwe_1230

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_1230
# title: "CWE-1230: Exposure of Sensitive Information Through Metadata"
# methodology: >
#   The product prevents direct access to a resource containing sensitive information, but it does not sufficiently limit access to metadata that is derived from the original, sensitive information.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-1230" in assertion.predicate.content.tags
    }
}