package openssf.omega.policy.autogenerated.cwe.cwe_58

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_58
# title: "CWE-58: Path Equivalence: Windows 8.3 Filename"
# methodology: >
#   The product contains a protection mechanism that restricts access to a long filename on a Windows operating system, but it does not properly restrict access to the equivalent short "8.3" filename.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-58" in assertion.predicate.content.tags
    }
}