package openssf.omega.policy.autogenerated.cwe.cwe_188

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_188
# title: "CWE-188: Reliance on Data/Memory Layout"
# methodology: >
#   The product makes invalid assumptions about how protocol data or memory is organized at a lower level, resulting in unintended program behavior.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-188" in assertion.predicate.content.tags
    }
}