package openssf.omega.policy.autogenerated.cwe.cwe_609

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_609
# title: "CWE-609: Double-Checked Locking"
# methodology: >
#   The product uses double-checked locking to access a resource without the overhead of explicit synchronization, but the locking is insufficient.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-609" in assertion.predicate.content.tags
    }
}