package openssf.omega.policy.autogenerated.cwe.cwe_637

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_637
# title: "CWE-637: Unnecessary Complexity in Protection Mechanism (Not Using 'Economy of Mechanism')"
# methodology: >
#   The product uses a more complex mechanism than necessary, which could lead to resultant weaknesses when the mechanism is not correctly understood, modeled, configured, implemented, or used.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-637" in assertion.predicate.content.tags
    }
}