package openssf.omega.policy.autogenerated.cwe.cwe_598

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_598
# title: "CWE-598: Use of GET Request Method With Sensitive Query Strings"
# methodology: >
#   The web application uses the HTTP GET method to process a request and includes sensitive information in the query string of that request.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-598" in assertion.predicate.content.tags
    }
}