package openssf.omega.policy.autogenerated.cwe.cwe_353

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_353
# title: "CWE-353: Missing Support for Integrity Check"
# methodology: >
#   The product uses a transmission protocol that does not include a mechanism for verifying the integrity of the data during transmission, such as a checksum.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-353" in assertion.predicate.content.tags
    }
}