package openssf.omega.policy.autogenerated.cwe.cwe_22

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_22
# title: "CWE-22: Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')"
# methodology: >
#   The product uses external input to construct a pathname that is intended to identify a file or directory that is located underneath a restricted parent directory, but the product does not properly neutralize special elements within the pathname that can cause the pathname to resolve to a location that is outside of the restricted directory.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-22" in assertion.predicate.content.tags
    }
}