package openssf.omega.policy.autogenerated.cwe.cwe_118

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_118
# title: "CWE-118: Incorrect Access of Indexable Resource ('Range Error')"
# methodology: >
#   The product does not restrict or incorrectly restricts operations within the boundaries of a resource that is accessed using an index or pointer, such as memory or files.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-118" in assertion.predicate.content.tags
    }
}