package openssf.omega.policy.autogenerated.cwe.cwe_99

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_99
# title: "CWE-99: Improper Control of Resource Identifiers ('Resource Injection')"
# methodology: >
#   The product receives input from an upstream component, but it does not restrict or incorrectly restricts the input before it is used as an identifier for a resource that may be outside the intended sphere of control.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-99" in assertion.predicate.content.tags
    }
}