package openssf.omega.policy.autogenerated.cwe.cwe_825

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_825
# title: "CWE-825: Expired Pointer Dereference"
# methodology: >
#   The product dereferences a pointer that contains a location for memory that was previously valid, but is no longer valid.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-825" in assertion.predicate.content.tags
    }
}