package openssf.omega.policy.autogenerated.cwe.cwe_88

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_88
# title: "CWE-88: Improper Neutralization of Argument Delimiters in a Command ('Argument Injection')"
# methodology: >
#   The product constructs a string for a command to be executed by a separate component in another control sphere, but it does not properly delimit the intended arguments, options, or switches within that command string.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-88" in assertion.predicate.content.tags
    }
}