package openssf.omega.policy.autogenerated.cwe.cwe_648

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_648
# title: "CWE-648: Incorrect Use of Privileged APIs"
# methodology: >
#   The product does not conform to the API requirements for a function call that requires extra privileges. This could allow attackers to gain privileges by causing the function to be called incorrectly.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-648" in assertion.predicate.content.tags
    }
}