package openssf.omega.policy.autogenerated.cwe.cwe_1249

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_1249
# title: "CWE-1249: Application-Level Admin Tool with Inconsistent View of Underlying Operating System"
# methodology: >
#   The product provides an application for administrators to manage parts of the underlying operating system, but the application does not accurately identify all of the relevant entities or resources that exist in the OS; that is, the application's model of the OS's state is inconsistent with the OS's actual state.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-1249" in assertion.predicate.content.tags
    }
}