package openssf.omega.policy.autogenerated.cwe.cwe_241

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_241
# title: "CWE-241: Improper Handling of Unexpected Data Type"
# methodology: >
#   The product does not handle or incorrectly handles when a particular element is not the expected type, e.g. it expects a digit (0-9) but is provided with a letter (A-Z).
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-241" in assertion.predicate.content.tags
    }
}