package openssf.omega.policy.autogenerated.cwe.cwe_336

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_336
# title: "CWE-336: Same Seed in Pseudo-Random Number Generator (PRNG)"
# methodology: >
#   A Pseudo-Random Number Generator (PRNG) uses the same seed each time the product is initialized.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-336" in assertion.predicate.content.tags
    }
}