package openssf.omega.policy.autogenerated.cwe.cwe_614

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_614
# title: "CWE-614: Sensitive Cookie in HTTPS Session Without 'Secure' Attribute"
# methodology: >
#   The Secure attribute for sensitive cookies in HTTPS sessions is not set, which could cause the user agent to send those cookies in plaintext over an HTTP session.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-614" in assertion.predicate.content.tags
    }
}