package openssf.omega.policy.autogenerated.cwe.cwe_1274

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_1274
# title: "CWE-1274: Improper Access Control for Volatile Memory Containing Boot Code"
# methodology: >
#   The product conducts a secure-boot process that transfers bootloader code from Non-Volatile Memory (NVM) into Volatile Memory (VM), but it does not have sufficient access control or other protections for the Volatile Memory.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-1274" in assertion.predicate.content.tags
    }
}