package openssf.omega.policy.autogenerated.cwe.cwe_243

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_243
# title: "CWE-243: Creation of chroot Jail Without Changing Working Directory"
# methodology: >
#   The product uses the chroot() system call to create a jail, but does not change the working directory afterward. This does not prevent access to files outside of the jail.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-243" in assertion.predicate.content.tags
    }
}