package openssf.omega.policy.autogenerated.cwe.cwe_772

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_772
# title: "CWE-772: Missing Release of Resource after Effective Lifetime"
# methodology: >
#   The product does not release a resource after its effective lifetime has ended, i.e., after the resource is no longer needed.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-772" in assertion.predicate.content.tags
    }
}