package openssf.omega.policy.autogenerated.cwe.cwe_223

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_223
# title: "CWE-223: Omission of Security-relevant Information"
# methodology: >
#   The product does not record or display information that would be important for identifying the source or nature of an attack, or determining if an action is safe.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-223" in assertion.predicate.content.tags
    }
}