package openssf.omega.policy.autogenerated.cwe.cwe_1250

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_1250
# title: "CWE-1250: Improper Preservation of Consistency Between Independent Representations of Shared State"
# methodology: >
#   The product has or supports multiple distributed components or sub-systems that are each required to keep their own local copy of shared data - such as state or cache - but the product does not ensure that all local copies remain consistent with each other.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-1250" in assertion.predicate.content.tags
    }
}