package openssf.omega.policy.autogenerated.cwe.cwe_1262

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_1262
# title: "CWE-1262: Improper Access Control for Register Interface"
# methodology: >
#   The product uses memory-mapped I/O registers that act as an interface to hardware functionality from software, but there is improper access control to those registers.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-1262" in assertion.predicate.content.tags
    }
}