package openssf.omega.policy.autogenerated.cwe.cwe_1023

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_1023
# title: "CWE-1023: Incomplete Comparison with Missing Factors"
# methodology: >
#   The product performs a comparison between entities that must consider multiple factors or characteristics of each entity, but the comparison does not include one or more of these factors.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-1023" in assertion.predicate.content.tags
    }
}