package openssf.omega.policy.autogenerated.cwe.cwe_214

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_214
# title: "CWE-214: Invocation of Process Using Visible Sensitive Information"
# methodology: >
#   A process is invoked with sensitive command-line arguments, environment variables, or other elements that can be seen by other processes on the operating system.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-214" in assertion.predicate.content.tags
    }
}