package openssf.omega.policy.autogenerated.cwe.cwe_785

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_785
# title: "CWE-785: Use of Path Manipulation Function without Maximum-sized Buffer"
# methodology: >
#   The product invokes a function for normalizing paths or file names, but it provides an output buffer that is smaller than the maximum possible size, such as PATH_MAX.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-785" in assertion.predicate.content.tags
    }
}