package openssf.omega.policy.autogenerated.cwe.cwe_806

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_806
# title: "CWE-806: Buffer Access Using Size of Source Buffer"
# methodology: >
#   The product uses the size of a source buffer when reading from or writing to a destination buffer, which may cause it to access memory that is outside of the bounds of the buffer.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-806" in assertion.predicate.content.tags
    }
}