package openssf.omega.policy.autogenerated.cwe.cwe_1258

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_1258
# title: "CWE-1258: Exposure of Sensitive System Information Due to Uncleared Debug Information"
# methodology: >
#   The hardware does not fully clear security-sensitive values, such as keys and intermediate values in cryptographic operations, when debug mode is entered.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-1258" in assertion.predicate.content.tags
    }
}