package openssf.omega.policy.autogenerated.cwe.cwe_159

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_159
# title: "CWE-159: Improper Handling of Invalid Use of Special Elements"
# methodology: >
#   The product does not properly filter, remove, quote, or otherwise manage the invalid use of special elements in user-controlled input, which could cause adverse effect on its behavior and integrity.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-159" in assertion.predicate.content.tags
    }
}