package openssf.omega.policy.autogenerated.cwe.cwe_822

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_822
# title: "CWE-822: Untrusted Pointer Dereference"
# methodology: >
#   The product obtains a value from an untrusted source, converts this value to a pointer, and dereferences the resulting pointer.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-822" in assertion.predicate.content.tags
    }
}