package openssf.omega.policy.autogenerated.cwe.cwe_572

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_572
# title: "CWE-572: Call to Thread run() instead of start()"
# methodology: >
#   The product calls a thread's run() method instead of calling start(), which causes the code to run in the thread of the caller instead of the callee.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-572" in assertion.predicate.content.tags
    }
}