package openssf.omega.policy.autogenerated.cwe.cwe_1177

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_1177
# title: "CWE-1177: Use of Prohibited Code"
# methodology: >
#   The product uses a function, library, or third party component that has been explicitly prohibited, whether by the developer or the customer.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-1177" in assertion.predicate.content.tags
    }
}