package openssf.omega.policy.autogenerated.cwe.cwe_1312

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_1312
# title: "CWE-1312: Missing Protection for Mirrored Regions in On-Chip Fabric Firewall"
# methodology: >
#   The firewall in an on-chip fabric protects the main addressed region, but it does not protect any mirrored memory or memory-mapped-IO (MMIO) regions.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-1312" in assertion.predicate.content.tags
    }
}