package openssf.omega.policy.autogenerated.cwe.cwe_615

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_615
# title: "CWE-615: Inclusion of Sensitive Information in Source Code Comments"
# methodology: >
#   While adding general comments is very useful, some programmers tend to leave important data, such as: filenames related to the web application, old links or links which were not meant to be browsed by users, old code fragments, etc.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-615" in assertion.predicate.content.tags
    }
}