package openssf.omega.policy.autogenerated.cwe.cwe_942

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_942
# title: "CWE-942: Permissive Cross-domain Policy with Untrusted Domains"
# methodology: >
#   The product uses a cross-domain policy file that includes domains that should not be trusted.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-942" in assertion.predicate.content.tags
    }
}