package openssf.omega.policy.autogenerated.cwe.cwe_687

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_687
# title: "CWE-687: Function Call With Incorrectly Specified Argument Value"
# methodology: >
#   The product calls a function, procedure, or routine, but the caller specifies an argument that contains the wrong value, which may lead to resultant weaknesses.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-687" in assertion.predicate.content.tags
    }
}