package openssf.omega.policy.autogenerated.cwe.cwe_602

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_602
# title: "CWE-602: Client-Side Enforcement of Server-Side Security"
# methodology: >
#   The product is composed of a server that relies on the client to implement a mechanism that is intended to protect the server.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-602" in assertion.predicate.content.tags
    }
}