package openssf.omega.policy.autogenerated.cwe.cwe_1050

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_1050
# title: "CWE-1050: Excessive Platform Resource Consumption within a Loop"
# methodology: >
#   The product has a loop body or loop condition that contains a control element that directly or indirectly consumes platform resources, e.g. messaging, sessions, locks, or file descriptors.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-1050" in assertion.predicate.content.tags
    }
}