package openssf.omega.policy.autogenerated.cwe.cwe_406

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_406
# title: "CWE-406: Insufficient Control of Network Message Volume (Network Amplification)"
# methodology: >
#   The product does not sufficiently monitor or control transmitted network traffic volume, so that an actor can cause the product to transmit more traffic than should be allowed for that actor.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-406" in assertion.predicate.content.tags
    }
}