package openssf.omega.policy.autogenerated.cwe.cwe_666

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_666
# title: "CWE-666: Operation on Resource in Wrong Phase of Lifetime"
# methodology: >
#   The product performs an operation on a resource at the wrong phase of the resource's lifecycle, which can lead to unexpected behaviors.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-666" in assertion.predicate.content.tags
    }
}