package openssf.omega.policy.autogenerated.cwe.cwe_1325

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_1325
# title: "CWE-1325: Improperly Controlled Sequential Memory Allocation"
# methodology: >
#   The product manages a group of objects or resources and performs a separate memory allocation for each object, but it does not properly limit the total amount of memory that is consumed by all of the combined objects.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-1325" in assertion.predicate.content.tags
    }
}