package openssf.omega.policy.autogenerated.cwe.cwe_1244

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_1244
# title: "CWE-1244: Internal Asset Exposed to Unsafe Debug Access Level or State"
# methodology: >
#   The product uses physical debug or test interfaces with support for multiple access levels, but it assigns the wrong debug access level to an internal asset, providing unintended access to the asset from untrusted debug agents.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-1244" in assertion.predicate.content.tags
    }
}