package openssf.omega.policy.autogenerated.cwe.cwe_233

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_233
# title: "CWE-233: Improper Handling of Parameters"
# methodology: >
#   The product does not properly handle when the expected number of parameters, fields, or arguments is not provided in input, or if those parameters are undefined.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-233" in assertion.predicate.content.tags
    }
}