package openssf.omega.policy.autogenerated.cwe.cwe_392

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_392
# title: "CWE-392: Missing Report of Error Condition"
# methodology: >
#   The product encounters an error but does not provide a status code or return value to indicate that an error has occurred.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-392" in assertion.predicate.content.tags
    }
}