package openssf.omega.policy.autogenerated.cwe.cwe_439

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_439
# title: "CWE-439: Behavioral Change in New Version or Environment"
# methodology: >
#   A's behavior or functionality changes with a new version of A, or a new environment, which is not known (or manageable) by B.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-439" in assertion.predicate.content.tags
    }
}