package openssf.omega.policy.autogenerated.cwe.cwe_1191

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_1191
# title: "CWE-1191: On-Chip Debug and Test Interface With Improper Access Control"
# methodology: >
#   The chip does not implement or does not correctly perform access control to check whether users are authorized to access internal registers and test modes through the physical debug/test interface.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-1191" in assertion.predicate.content.tags
    }
}