package openssf.omega.policy.autogenerated.cwe.cwe_1299

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_1299
# title: "CWE-1299: Missing Protection Mechanism for Alternate Hardware Interface"
# methodology: >
#   The lack of protections on alternate paths to access control-protected assets (such as unprotected shadow registers and other external facing unguarded interfaces) allows an attacker to bypass existing protections to the asset that are only performed against the primary path.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-1299" in assertion.predicate.content.tags
    }
}