package openssf.omega.policy.autogenerated.cwe.cwe_307

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_307
# title: "CWE-307: Improper Restriction of Excessive Authentication Attempts"
# methodology: >
#   The product does not implement sufficient measures to prevent multiple failed authentication attempts within a short time frame, making it more susceptible to brute force attacks.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-307" in assertion.predicate.content.tags
    }
}