package openssf.omega.policy.autogenerated.cwe.cwe_923

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_923
# title: "CWE-923: Improper Restriction of Communication Channel to Intended Endpoints"
# methodology: >
#   The product establishes a communication channel to (or from) an endpoint for privileged or protected operations, but it does not properly ensure that it is communicating with the correct endpoint.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-923" in assertion.predicate.content.tags
    }
}