package openssf.omega.policy.autogenerated.cwe.cwe_1099

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_1099
# title: "CWE-1099: Inconsistent Naming Conventions for Identifiers"
# methodology: >
#   The product's code, documentation, or other artifacts do not consistently use the same naming conventions for variables, callables, groups of related callables, I/O capabilities, data types, file names, or similar types of elements.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-1099" in assertion.predicate.content.tags
    }
}