package openssf.omega.policy.autogenerated.cwe.cwe_690

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_690
# title: "CWE-690: Unchecked Return Value to NULL Pointer Dereference"
# methodology: >
#   The product does not check for an error after calling a function that can return with a NULL pointer if the function fails, which leads to a resultant NULL pointer dereference.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-690" in assertion.predicate.content.tags
    }
}