package openssf.omega.policy.autogenerated.cwe.cwe_830

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_830
# title: "CWE-830: Inclusion of Web Functionality from an Untrusted Source"
# methodology: >
#   The product includes web functionality (such as a web widget) from another domain, which causes it to operate within the domain of the product, potentially granting total access and control of the product to the untrusted source.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-830" in assertion.predicate.content.tags
    }
}