package openssf.omega.policy.autogenerated.cwe.cwe_1022

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_1022
# title: "CWE-1022: Use of Web Link to Untrusted Target with window.opener Access"
# methodology: >
#   The web application produces links to untrusted external sites outside of its sphere of control, but it does not properly prevent the external site from modifying security-critical properties of the window.opener object, such as the location property.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-1022" in assertion.predicate.content.tags
    }
}