package openssf.omega.policy.autogenerated.cwe.cwe_1319

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_1319
# title: "CWE-1319: Improper Protection against Electromagnetic Fault Injection (EM-FI)"
# methodology: >
#   The device is susceptible to electromagnetic fault injection attacks, causing device internal information to be compromised or security mechanisms to be bypassed.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-1319" in assertion.predicate.content.tags
    }
}