package openssf.omega.policy.autogenerated.cwe.cwe_296

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_296
# title: "CWE-296: Improper Following of a Certificate's Chain of Trust"
# methodology: >
#   The product does not follow, or incorrectly follows, the chain of trust for a certificate back to a trusted root certificate, resulting in incorrect trust of any resource that is associated with that certificate.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-296" in assertion.predicate.content.tags
    }
}