package openssf.omega.policy.autogenerated.cwe.cwe_454

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_454
# title: "CWE-454: External Initialization of Trusted Variables or Data Stores"
# methodology: >
#   The product initializes critical internal variables or data stores using inputs that can be modified by untrusted actors.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-454" in assertion.predicate.content.tags
    }
}