package openssf.omega.policy.autogenerated.cwe.cwe_472

# Metadata (YAML)
# ---
# name: autogenerated.cwe.cwe_472
# title: "CWE-472: External Control of Assumed-Immutable Web Parameter"
# methodology: >
#   The web application does not sufficiently verify inputs that are assumed to be immutable but are actually externally controllable, such as hidden form fields.
# version: 0.1.0
# last_updated:
#   date: 2023-05-25
#   author: Michael Scovetta <michael.scovetta@gmail.com>
# ---

import future.keywords.every
import future.keywords.in

default pass = false
default applies = false

# Identify whether this policy applies to a given data object
applies := true {
    input.predicate.generator.name == "openssf.omega.security_tool_finding"
    input.predicateType == "https://github.com/ossf/alpha-omega/security_tool_finding/0.1.0"
    input.predicate.content.tags
}

pass := true {
    every assertion in input {
        not "cwe-472" in assertion.predicate.content.tags
    }
}