# Generated by Django 3.2.9 on 2021-11-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0004_tooldefect_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
