# Generated by Django 4.0 on 2021-12-08 02:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0006_remove_filter_definition_remove_filter_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
