# Generated by Django 4.0 on 2021-12-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0010_tooldefect_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='last_executed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
