# Generated by Django 4.0 on 2021-12-23 06:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0011_filter_last_executed'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.BinaryField(db_index=True, max_length=32)),
                ('content_type', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('data', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='finding',
            name='file_path',
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(db_index=True, max_length=512)),
                ('path', models.CharField(db_index=True, max_length=4096)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triage.filecontent')),
            ],
        ),
        migrations.AddField(
            model_name='finding',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='triage.file'),
        ),
        migrations.AddField(
            model_name='scan',
            name='files',
            field=models.ManyToManyField(blank=True, to='triage.File'),
        ),
    ]
