# Generated by Django 4.0 on 2021-12-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0012_filecontent_remove_finding_file_path_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectversion',
            name='files',
            field=models.ManyToManyField(blank=True, to='triage.File'),
        ),
    ]
