# Generated by Django 4.0 on 2021-12-23 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0013_projectversion_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finding',
            name='scan',
        ),
        migrations.AddField(
            model_name='finding',
            name='normalized_title',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='project_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triage.projectversion'),
        ),
        migrations.AddField(
            model_name='finding',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='triage.tool'),
        ),
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='triage.filecontent'),
        ),
        migrations.AlterField(
            model_name='projectversion',
            name='files',
            field=models.ManyToManyField(blank=True, editable=False, to='triage.File'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='version',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
