# Generated by Django 4.0 on 2021-12-31 06:49

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0017_tooldefect_created_at_tooldefect_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tooldefect',
            managers=[
                ('active_tool_defects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='case',
            old_name='report_foreign_reference',
            new_name='reporting_reference',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='resolved_dt',
            new_name='resolved_actual_dt',
        ),
        migrations.RemoveField(
            model_name='case',
            name='assigned_dt',
        ),
        migrations.AlterField(
            model_name='case',
            name='reporting_partner',
            field=models.CharField(blank=True, choices=[('N', 'None'), ('GS', 'GitHub Security Lab'), ('CT', 'CERT'), ('MS', 'Microsoft Security Response Center'), ('NS', 'Not Specified')], default='NS', max_length=2, null=True),
        ),
    ]
