# Generated by Django 4.0 on 2022-01-03 19:31

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0024_wikiarticlerevision_change_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wikiarticle',
            options={'ordering': ['slug']},
        ),
        migrations.AlterModelOptions(
            name='wikiarticlerevision',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelManagers(
            name='wikiarticle',
            managers=[
                ('active_wiki_articles', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='wikiarticlerevision',
            name='state',
        ),
        migrations.AddField(
            model_name='wikiarticle',
            name='state',
            field=models.CharField(choices=[('N', 'New'), ('A', 'Active'), ('R', 'Resolved'), ('D', 'Deleted'), ('CL', 'Closed'), ('NS', 'Not Specified')], default='A', max_length=2),
        ),
    ]
