# Generated by Django 4.1.3 on 2022-12-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triage", "0026_alter_attachment_uuid_alter_case_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file_type",
            field=models.CharField(
                choices=[("S", "Source Code"), ("R", "Scan Result"), ("U", "Unknown")],
                db_index=True,
                default="U",
                max_length=64,
            ),
        ),
    ]
