# Generated by Django 4.1.3 on 2022-12-18 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("triage", "0028_remove_file_content_file_content_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="storage_key",
            new_name="file_key",
        ),
    ]
