# Generated by Django 4.1.7 on 2023-03-03 04:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assertion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generator', models.CharField(max_length=1024)),
                ('subject', models.CharField(max_length=1024)),
                ('content', models.JSONField()),
            ],
        ),
    ]
