# Generated by Django 4.1.7 on 2023-03-09 21:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assertion",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("content", models.JSONField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AssertionGenerator",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("version", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("identifier", models.CharField(max_length=1024)),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="PolicyEvaluationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PA", "Passed"),
                            ("FA", "Failed"),
                            ("IN", "Indeterminate"),
                            ("UK", "Unknown"),
                        ],
                        default="UK",
                        max_length=2,
                    ),
                ),
                ("evaluated_by", models.CharField(max_length=1024)),
                ("evaluation_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("subject_type", models.CharField(max_length=1024)),
                ("identifier", models.CharField(db_index=True, max_length=1024)),
            ],
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["subject_type", "identifier"], name="oaffe_subje_subject_63bb03_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(fields=("subject_type", "identifier"), name="sti"),
        ),
        migrations.AddField(
            model_name="policyevaluationresult",
            name="policy",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="oaffe.policy"),
        ),
        migrations.AddField(
            model_name="policyevaluationresult",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="oaffe.subject"
            ),
        ),
        migrations.AddField(
            model_name="assertion",
            name="generator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="oaffe.assertiongenerator"
            ),
        ),
        migrations.AddField(
            model_name="assertion",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="oaffe.subject"
            ),
        ),
    ]
