# Generated by Django 4.1.7 on 2023-03-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oaffe", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="policyevaluationresult",
            options={"ordering": ["evaluation_date"]},
        ),
        migrations.AddField(
            model_name="assertiongenerator",
            name="name_readable",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
