# Generated by Django 4.1.7 on 2023-03-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaffe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=1024)),
                ('policy', models.CharField(max_length=1024)),
                ('status', models.BooleanField()),
                ('updated_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
