# Generated by Django 4.1.7 on 2023-03-11 23:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("oaffe", "0003_policygroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageRequest",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("package", models.CharField(max_length=1024)),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_date"],
            },
        ),
    ]
