# Generated by Django 4.1.7 on 2023-03-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oaffe", "0004_packagerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="icon_class",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
