# Generated by Django 4.1.7 on 2023-05-22 05:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("oaffe", "0005_policy_icon_class"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyEvaluationQueue",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("N", "New"), ("IP", "In Progress"), ("CO", "Completed")],
                        default="N",
                        max_length=2,
                    ),
                ),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oaffe.subject"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Refresh Queue Items",
                "ordering": ["updated_date"],
            },
        ),
    ]
